### ISSUE TITLE
create_order returns an incorrect want_amount when side="sell"

### ISSUE THREAD

**Issue by junw3i** [KeithSSmith/switcheo-python#17]
Using `quantity` instead of `want_amount` when constructing order_params should be an easier approach

**Comment by KeithSSmith** [comment]
I like this idea and putting it in the SwitcheoClient class is where I would want to put it b/c I envision everyone just using that class to interact with everything (all other classes would be accessible).  Also, the SwitcheoClient would just abstract the order function in the AuthenticatedClient which I'm trying to keep in line with Switcheo's official documentation (https://docs.switcheo.network/#the-order-model).

I would propose that a `buy_order` and `sell_order` is created in `SwitcheoClient` to be a bit more straight forward on what has to be passed to the `order` function b/c it is still confusing at times.

**Comment by KeithSSmith** [comment]
Can you expand on this with an example request?  I'm not sure I'm interpreting this request as intended b/c `want_amount` comes from the response to the Switcheo API, so if this is coming back with an incorrect value we should look into it further.  I do think the order API is a bit confusing b/c it seems backwards to new users (has been talked about in the Switcheo Slack channel).  Which is why I'm proposing abstracting the order into buy and sell to make it a little bit more straight forward.

**Comment by junw3i** [comment]
The official docs have been updated to with `quantity` instead of `want_amount`
https://docs.switcheo.network/#post-create-order

`want_amount` is still supported but the order params should be much easier to construct with the use of `quantity`

**Comment by KeithSSmith** [comment]
Thank you @junw3i, this is a much appreciated change and something that makes interacting with the order endpoint much cleaner!

This has been updated as part of PR #21
